"""
Connected-inbox endpoints, shared by every role (admin, candidate, staff,
superuser).

/connect-url and /status and DELETE and /smtp are behind normal bearer auth
(any role). The OAuth callback (/api/oauth/google/callback) is NOT --
Google's redirect is a plain browser navigation with no Authorization
header, so identity is instead carried in the signed `state` param (a
short-lived JWT-like token, role='oauth_state', embedding
owner_type+owner_id) generated by /connect-url and verified on callback.
This prevents both CSRF (state is unguessable and single-purpose) and
account-linking attacks (an attacker can't complete their own Google
consent and have it attached to someone else's account, since state is
bound to whoever initiated the flow).

Two ways to connect: OAuth (Gmail, preferred -- the app never sees a real
password) or manual SMTP entry (/smtp -- for any other provider). Either
way, the secret is encrypted at rest (services/crypto.py) and NEVER
returned by any endpoint here, including /status -- once saved, a
password/refresh-token is write-only from the API's perspective.
"""
from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import RedirectResponse
from jose import JWTError
from pydantic import BaseModel, EmailStr
from sqlalchemy.orm import Session

from api.auth import create_access_token, decode_access_token
from api.deps import _decode_or_401, _oauth2_scheme, get_db
from db.models import AdminUser, Candidate, EmailAccountCredential, Staff, SuperUser
from services.crypto import encrypt_secret
from services.google_oauth import build_consent_url, exchange_code_for_tokens, revoke_token

router = APIRouter(tags=["email-account"])

STATE_EXPIRE_MINUTES = 10

_PROFILE_REDIRECT = {
    "admin": "/admin/profile",
    "candidate": "/candidate/profile",
    "staff": "/staff/profile",
    "superuser": "/superuser/profile",
}


def get_current_email_account_owner(
    token: str | None = Depends(_oauth2_scheme),
    db: Session = Depends(get_db),
) -> tuple[str, int]:
    """Resolves (owner_type, owner_id) for whoever's calling -- candidate,
    admin, staff, superuser, or an individual-account admin acting on
    their own linked candidate (same resolution api/deps.py::get_current_candidate
    already does; preserved here so those accounts keep connecting email
    to their candidate profile)."""
    payload = _decode_or_401(token)
    role = payload.get("role")

    if role == "candidate":
        candidate = db.query(Candidate).filter_by(id=payload.get("candidate_id")).one_or_none()
        if candidate is None:
            raise HTTPException(status_code=401, detail="Could not validate credentials")
        return ("candidate", candidate.id)

    if role == "admin":
        admin = db.query(AdminUser).filter_by(username=payload["sub"]).one_or_none()
        if admin is None:
            raise HTTPException(status_code=401, detail="Could not validate credentials")
        linked_claim = payload.get("linked_candidate_id")
        if linked_claim and admin.linked_candidate_id == linked_claim:
            candidate = db.query(Candidate).filter_by(id=admin.linked_candidate_id).one_or_none()
            if candidate is not None:
                return ("candidate", candidate.id)
        return ("admin", admin.id)

    if role == "staff":
        staff = db.query(Staff).filter_by(username=payload["sub"], is_active=True).one_or_none()
        if staff is None:
            raise HTTPException(status_code=401, detail="Could not validate credentials")
        return ("staff", staff.id)

    if role == "superuser":
        superuser = db.query(SuperUser).filter_by(username=payload["sub"]).one_or_none()
        if superuser is None:
            raise HTTPException(status_code=401, detail="Could not validate credentials")
        return ("superuser", superuser.id)

    raise HTTPException(status_code=403, detail="Access required")


@router.get("/api/me/email-account/connect-url")
def get_connect_url(owner: tuple[str, int] = Depends(get_current_email_account_owner)):
    owner_type, owner_id = owner
    state = create_access_token(
        subject=f"oauth_state:{owner_type}:{owner_id}",
        role="oauth_state",
        extra_claims={"owner_type": owner_type, "owner_id": owner_id},
        expires_minutes=STATE_EXPIRE_MINUTES,
    )
    try:
        url = build_consent_url(state)
    except RuntimeError as e:
        raise HTTPException(status_code=503, detail=str(e))
    return {"consent_url": url}


@router.get("/api/oauth/google/callback")
def google_oauth_callback(
    code: str = Query(...),
    state: str = Query(...),
    db: Session = Depends(get_db),
):
    try:
        payload = decode_access_token(state)
    except JWTError:
        raise HTTPException(status_code=400, detail="Invalid or expired OAuth state -- please reconnect.")
    if payload.get("role") != "oauth_state":
        raise HTTPException(status_code=400, detail="Invalid OAuth state.")

    owner_type = payload.get("owner_type")
    owner_id = payload.get("owner_id")
    owner_model = {"candidate": Candidate, "admin": AdminUser, "staff": Staff, "superuser": SuperUser}.get(owner_type)
    owner = db.query(owner_model).filter_by(id=owner_id).one_or_none() if owner_model else None
    if owner is None:
        raise HTTPException(status_code=404, detail="Account not found for this OAuth state.")

    try:
        tokens = exchange_code_for_tokens(code)
    except Exception as e:  # noqa: BLE001 -- surface as a clear connect failure, not a 500
        raise HTTPException(status_code=502, detail=f"Google token exchange failed: {e}")

    if not tokens.refresh_token:
        raise HTTPException(
            status_code=422,
            detail=(
                "Google did not return a refresh token -- this usually means the account "
                "already has a prior grant for this app. Revoke access at "
                "https://myaccount.google.com/permissions and try connecting again."
            ),
        )

    existing = (
        db.query(EmailAccountCredential)
        .filter_by(owner_type=owner_type, owner_id=owner_id, provider="gmail")
        .one_or_none()
    )
    if existing is None:
        existing = EmailAccountCredential(owner_type=owner_type, owner_id=owner_id, provider="gmail")
        db.add(existing)

    existing.account_email = tokens.account_email
    existing.secret_type = "oauth_refresh_token"
    existing.encrypted_secret = encrypt_secret(tokens.refresh_token)
    existing.scopes_granted = tokens.granted_scopes
    existing.status = "connected"
    existing.last_error = None
    db.commit()

    # Redirect back into the SPA rather than returning raw JSON -- this
    # request is a top-level browser navigation from Google, not an API
    # call the frontend JS initiated.
    redirect_path = _PROFILE_REDIRECT.get(owner_type, "/login")
    return RedirectResponse(url=f"{redirect_path}?email_connected=1")


@router.get("/api/me/email-account")
def email_account_status(owner: tuple[str, int] = Depends(get_current_email_account_owner), db: Session = Depends(get_db)):
    owner_type, owner_id = owner
    row = db.query(EmailAccountCredential).filter_by(owner_type=owner_type, owner_id=owner_id).one_or_none()
    if row is None:
        return {"connected": False}
    return {
        "connected": row.status == "connected",
        "provider": row.provider,
        "account_email": row.account_email,
        "smtp_host": row.smtp_host,
        "smtp_port": row.smtp_port,
        "imap_host": row.imap_host,
        "imap_port": row.imap_port,
        "smtp_username": row.smtp_username,
        "scopes_granted": row.scopes_granted,
        "status": row.status,
        "connected_at": row.connected_at,
    }


@router.delete("/api/me/email-account")
def disconnect_email_account(owner: tuple[str, int] = Depends(get_current_email_account_owner), db: Session = Depends(get_db)):
    owner_type, owner_id = owner
    row = db.query(EmailAccountCredential).filter_by(owner_type=owner_type, owner_id=owner_id).one_or_none()
    if row is None:
        raise HTTPException(status_code=404, detail="No connected email account.")

    from services.crypto import decrypt_secret

    if row.secret_type == "oauth_refresh_token":
        try:
            secret = decrypt_secret(row.encrypted_secret)
            revoke_token(secret)
        except Exception:
            pass  # best-effort revoke at Google; the local row is deleted regardless

    db.delete(row)
    db.commit()
    return {"disconnected": True}


class SmtpConnectRequest(BaseModel):
    smtp_host: str
    smtp_port: int
    imap_host: str
    imap_port: int
    username: str
    account_email: EmailStr
    password: str


@router.put("/api/me/email-account/smtp")
def connect_smtp(
    payload: SmtpConnectRequest,
    owner: tuple[str, int] = Depends(get_current_email_account_owner),
    db: Session = Depends(get_db),
):
    """Manual-entry fallback for providers without OAuth2 -- captures
    both directions (SMTP for sending, IMAP for the future reply-reading
    phase), one shared username/password authenticating both, per
    EmailAccountCredential's docstring. The password is encrypted at
    rest (same mechanism as the Gmail refresh token) and is never
    returned by /status or any other response -- once saved, there is
    no API that reads it back out in plaintext or ciphertext."""
    owner_type, owner_id = owner
    existing = (
        db.query(EmailAccountCredential)
        .filter_by(owner_type=owner_type, owner_id=owner_id, provider="smtp")
        .one_or_none()
    )
    if existing is None:
        existing = EmailAccountCredential(owner_type=owner_type, owner_id=owner_id, provider="smtp")
        db.add(existing)

    existing.account_email = payload.account_email
    existing.smtp_host = payload.smtp_host
    existing.smtp_port = payload.smtp_port
    existing.imap_host = payload.imap_host
    existing.imap_port = payload.imap_port
    existing.smtp_username = payload.username
    existing.secret_type = "app_password"
    existing.encrypted_secret = encrypt_secret(payload.password)
    existing.status = "connected"
    existing.last_error = None
    db.commit()
    return {"connected": True, "provider": "smtp", "account_email": existing.account_email}
