"""
Connected-inbox endpoints, shared by admins and candidates.

/connect-url and /status and DELETE are behind normal bearer auth (either
role). The OAuth callback (/api/oauth/google/callback) is NOT -- Google's
redirect is a plain browser navigation with no Authorization header, so
identity is instead carried in the signed `state` param (a short-lived
JWT-like token, role='oauth_state', embedding owner_type+owner_id)
generated by /connect-url and verified on callback. This prevents both
CSRF (state is unguessable and single-purpose) and account-linking
attacks (an attacker can't complete their own Google consent and have it
attached to someone else's account, since state is bound to whoever
initiated the flow).
"""
from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import RedirectResponse
from jose import JWTError
from sqlalchemy.orm import Session

from api.auth import create_access_token, decode_access_token
from api.deps import _decode_or_401, _oauth2_scheme, get_db
from db.models import AdminUser, Candidate, EmailAccountCredential
from services.crypto import encrypt_secret
from services.google_oauth import build_consent_url, exchange_code_for_tokens, revoke_token

router = APIRouter(tags=["email-account"])

STATE_EXPIRE_MINUTES = 10


def get_current_email_account_owner(
    token: str | None = Depends(_oauth2_scheme),
    db: Session = Depends(get_db),
) -> tuple[str, int]:
    """Resolves (owner_type, owner_id) for whoever's calling -- a plain
    candidate, a plain admin, or an individual-account admin acting on
    their own linked candidate (same resolution api/deps.py::get_current_candidate
    already does; preserved here so those accounts keep connecting email
    to their candidate profile, exactly as before this endpoint supported
    admins at all)."""
    payload = _decode_or_401(token)
    role = payload.get("role")

    if role == "candidate":
        candidate = db.query(Candidate).filter_by(id=payload.get("candidate_id")).one_or_none()
        if candidate is None:
            raise HTTPException(status_code=401, detail="Could not validate credentials")
        return ("candidate", candidate.id)

    if role == "admin":
        admin = db.query(AdminUser).filter_by(username=payload["sub"]).one_or_none()
        if admin is None:
            raise HTTPException(status_code=401, detail="Could not validate credentials")
        linked_claim = payload.get("linked_candidate_id")
        if linked_claim and admin.linked_candidate_id == linked_claim:
            candidate = db.query(Candidate).filter_by(id=admin.linked_candidate_id).one_or_none()
            if candidate is not None:
                return ("candidate", candidate.id)
        return ("admin", admin.id)

    raise HTTPException(status_code=403, detail="Candidate or admin access required")


@router.get("/api/me/email-account/connect-url")
def get_connect_url(owner: tuple[str, int] = Depends(get_current_email_account_owner)):
    owner_type, owner_id = owner
    state = create_access_token(
        subject=f"oauth_state:{owner_type}:{owner_id}",
        role="oauth_state",
        extra_claims={"owner_type": owner_type, "owner_id": owner_id},
        expires_minutes=STATE_EXPIRE_MINUTES,
    )
    try:
        url = build_consent_url(state)
    except RuntimeError as e:
        raise HTTPException(status_code=503, detail=str(e))
    return {"consent_url": url}


@router.get("/api/oauth/google/callback")
def google_oauth_callback(
    code: str = Query(...),
    state: str = Query(...),
    db: Session = Depends(get_db),
):
    try:
        payload = decode_access_token(state)
    except JWTError:
        raise HTTPException(status_code=400, detail="Invalid or expired OAuth state -- please reconnect.")
    if payload.get("role") != "oauth_state":
        raise HTTPException(status_code=400, detail="Invalid OAuth state.")

    owner_type = payload.get("owner_type")
    owner_id = payload.get("owner_id")
    if owner_type == "candidate":
        owner = db.query(Candidate).filter_by(id=owner_id).one_or_none()
    elif owner_type == "admin":
        owner = db.query(AdminUser).filter_by(id=owner_id).one_or_none()
    else:
        owner = None
    if owner is None:
        raise HTTPException(status_code=404, detail="Account not found for this OAuth state.")

    try:
        tokens = exchange_code_for_tokens(code)
    except Exception as e:  # noqa: BLE001 -- surface as a clear connect failure, not a 500
        raise HTTPException(status_code=502, detail=f"Google token exchange failed: {e}")

    if not tokens.refresh_token:
        raise HTTPException(
            status_code=422,
            detail=(
                "Google did not return a refresh token -- this usually means the account "
                "already has a prior grant for this app. Revoke access at "
                "https://myaccount.google.com/permissions and try connecting again."
            ),
        )

    existing = (
        db.query(EmailAccountCredential)
        .filter_by(owner_type=owner_type, owner_id=owner_id, provider="gmail")
        .one_or_none()
    )
    if existing is None:
        existing = EmailAccountCredential(owner_type=owner_type, owner_id=owner_id, provider="gmail")
        db.add(existing)

    existing.account_email = tokens.account_email
    existing.secret_type = "oauth_refresh_token"
    existing.encrypted_secret = encrypt_secret(tokens.refresh_token)
    existing.scopes_granted = tokens.granted_scopes
    existing.status = "connected"
    existing.last_error = None
    db.commit()

    # Redirect back into the SPA rather than returning raw JSON -- this
    # request is a top-level browser navigation from Google, not an API
    # call the frontend JS initiated. Land admins and candidates back on
    # their own profile page.
    redirect_path = "/admin/profile" if owner_type == "admin" else "/candidate/profile"
    return RedirectResponse(url=f"{redirect_path}?email_connected=1")


@router.get("/api/me/email-account")
def email_account_status(owner: tuple[str, int] = Depends(get_current_email_account_owner), db: Session = Depends(get_db)):
    owner_type, owner_id = owner
    row = db.query(EmailAccountCredential).filter_by(owner_type=owner_type, owner_id=owner_id).one_or_none()
    if row is None:
        return {"connected": False}
    return {
        "connected": row.status == "connected",
        "provider": row.provider,
        "account_email": row.account_email,
        "scopes_granted": row.scopes_granted,
        "status": row.status,
        "connected_at": row.connected_at,
    }


@router.delete("/api/me/email-account")
def disconnect_email_account(owner: tuple[str, int] = Depends(get_current_email_account_owner), db: Session = Depends(get_db)):
    owner_type, owner_id = owner
    row = db.query(EmailAccountCredential).filter_by(owner_type=owner_type, owner_id=owner_id).one_or_none()
    if row is None:
        raise HTTPException(status_code=404, detail="No connected email account.")

    from services.crypto import decrypt_secret

    try:
        secret = decrypt_secret(row.encrypted_secret)
        revoke_token(secret)
    except Exception:
        pass  # best-effort revoke at Google; the local row is deleted regardless

    db.delete(row)
    db.commit()
    return {"disconnected": True}
